import { lazy } from "react";
import { z } from "zod";
import type { FlowComponent } from "../../types";
import { parseYaml, serializeYaml } from "../../utils/yaml";

export const SHEETS_ACTIONS = [
  "create_spreadsheet",
  "get_spreadsheet",
  "create_worksheet",
  "find_worksheet",
  "find_or_create_worksheet",
  "delete_worksheet",
  "rename_worksheet",
  "copy_worksheet",
  "change_sheet_properties",
  "create_row",
  "create_rows",
  "create_row_at_top",
  "get_row",
  "get_rows",
  "get_data_range",
  "lookup_row",
  "lookup_rows",
  "update_row",
  "update_rows",
  "clear_rows",
  "delete_rows",
  "create_column",
  "copy_range",
  "sort_range",
  "format_cells",
  "format_row",
  "set_data_validation",
  "create_conditional_formatting",
] as const;

export const SHEETS_PASTE = [
  "PASTE_NORMAL",
  "PASTE_VALUES",
  "PASTE_FORMAT",
  "PASTE_NO_BORDERS",
  "PASTE_FORMULA",
  "PASTE_DATA_VALIDATION",
  "PASTE_CONDITIONAL_FORMATTING",
] as const;

export const SHEETS_SORT = ["ASCENDING", "DESCENDING"] as const;

const configSchema = z.object({
  service_account_json: z.string(),
  oauth_connection: z.string(),
  delegate_to: z.string(),
  action: z.enum(SHEETS_ACTIONS),
  spreadsheet_id: z.string(),
  sheet_name: z.string(),
  title: z.string(),
  range: z.string(),
  row_number: z.string(),
  end_row_number: z.string(),
  column_name: z.string(),
  lookup_value: z.string(),
  values: z.string(),
  rows: z.string(),
  max_results: z.string(),
  new_name: z.string(),
  destination_spreadsheet_id: z.string(),
  source_range: z.string(),
  destination_range: z.string(),
  paste_type: z.enum(SHEETS_PASTE),
  sort_column_index: z.string(),
  sort_order: z.enum(SHEETS_SORT),
  bold: z.boolean(),
  italic: z.boolean(),
  strikethrough: z.boolean(),
  background_color: z.string(),
  foreground_color: z.string(),
  number_format: z.string(),
  frozen_rows: z.string(),
  frozen_columns: z.string(),
  hidden: z.boolean(),
  sheet_position: z.string(),
  validation_type: z.string(),
  validation_values: z.string(),
  condition_type: z.string(),
  condition_value: z.string(),
  condition_background_color: z.string(),
  include_headers: z.boolean(),
});
type Config = z.infer<typeof configSchema>;

const defaultConfig: Config = {
  service_account_json: "",
  oauth_connection: "",
  delegate_to: "",
  action: "get_spreadsheet",
  spreadsheet_id: "",
  sheet_name: "Sheet1",
  title: "",
  range: "",
  row_number: "0",
  end_row_number: "0",
  column_name: "",
  lookup_value: "",
  values: "",
  rows: "",
  max_results: "100",
  new_name: "",
  destination_spreadsheet_id: "",
  source_range: "",
  destination_range: "",
  paste_type: "PASTE_NORMAL",
  sort_column_index: "0",
  sort_order: "ASCENDING",
  bold: false,
  italic: false,
  strikethrough: false,
  background_color: "",
  foreground_color: "",
  number_format: "",
  frozen_rows: "0",
  frozen_columns: "0",
  hidden: false,
  sheet_position: "0",
  validation_type: "",
  validation_values: "",
  condition_type: "",
  condition_value: "",
  condition_background_color: "",
  include_headers: true,
};

const component: FlowComponent<Config> = {
  id: "google_sheets",
  name: "Google Sheets",
  category: "processor",
  description: "Performs Google Sheets operations.",
  configSchema,
  defaultConfig,
  parse: (s) => parseYaml(configSchema, s, defaultConfig),
  serialize: serializeYaml,
  Editor: lazy(() => import("./editor")),
};

export default component;
