import { param, type McpToolTemplate, type TemplatePack } from "./types";

function gsTool(
  id: string,
  name: string,
  description: string,
  action: string,
  parameters: ReturnType<typeof param>[],
  configOverrides: Record<string, string | number | boolean> = {},
): McpToolTemplate {
  return {
    id,
    name,
    description,
    parameters,
    processor: {
      component: "google_sheets",
      config: { action, ...configOverrides },
    },
  };
}

export const googleSheetsPack: TemplatePack = {
  id: "google_sheets",
  name: "Google Sheets",
  description: "28 MCP tools for managing Google Sheets spreadsheets, worksheets, rows, and formatting.",
  sharedConfig: [
    {
      key: "oauth_connection",
      title: "OAuth Connection",
      description: "Google OAuth connection. Set up in Connections page first.",
      type: "dynamic_select",
      required: true,
      dataSource: "connections",
    },
  ],
  templates: [
    gsTool(
      "gs_create_spreadsheet",
      "google_sheets_create_spreadsheet",
      "Create a new Google Sheets spreadsheet.",
      "create_spreadsheet",
      [
        param("title", "Title for the new spreadsheet", true),
        param("sheet_name", "Name for the first worksheet. Defaults to Sheet1."),
      ],
      {
        title: "${!this.title}",
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
      },
    ),
    gsTool(
      "gs_create_column",
      "google_sheets_create_column",
      "Create a new column in a specific spreadsheet.",
      "create_column",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("column_name", "Header name for the new column", true),
        param("values", "JSON array of values to populate the column"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        column_name: "${!this.column_name}",
        values: '${!this.values.or("")}',
      },
    ),
    gsTool(
      "gs_create_row",
      "google_sheets_create_row",
      "Create a new row in a specific spreadsheet.",
      "create_row",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("values", 'JSON array of values for the row, e.g. ["val1","val2"]', true),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        values: "${!this.values}",
      },
    ),
    gsTool(
      "gs_create_rows",
      "google_sheets_create_rows",
      "Create one or more new rows in a specific spreadsheet (with line item support).",
      "create_rows",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("rows", 'JSON array of arrays, e.g. [["a","b"],["c","d"]]', true),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        rows: "${!this.rows}",
      },
    ),
    gsTool(
      "gs_create_row_at_top",
      "google_sheets_create_row_at_top",
      "Creates a new spreadsheet row at the top of a spreadsheet (after the header row).",
      "create_row_at_top",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("values", "JSON array of values for the row", true),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        values: "${!this.values}",
      },
    ),
    gsTool(
      "gs_change_sheet_properties",
      "google_sheets_change_sheet_properties",
      "Update Google Sheets properties like frozen rows/columns, sheet position, and visibility settings.",
      "change_sheet_properties",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("frozen_rows", "Number of rows to freeze at the top", false, "number"),
        param("frozen_columns", "Number of columns to freeze on the left", false, "number"),
        param("hidden", "true or false"),
        param("sheet_position", "Position index of the sheet", false, "number"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        frozen_rows: '${!this.frozen_rows.or("0")}',
        frozen_columns: '${!this.frozen_columns.or("0")}',
        hidden: '${!this.hidden.or("false")}',
        sheet_position: '${!this.sheet_position.or("0")}',
      },
    ),
    gsTool(
      "gs_create_conditional_formatting",
      "google_sheets_create_conditional_formatting",
      "Apply conditional formatting to cells in a Google Sheets spreadsheet based on their values.",
      "create_conditional_formatting",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("range", "A1 notation range", true),
        param("condition_type", "Condition type: NUMBER_GREATER, TEXT_CONTAINS, CUSTOM_FORMULA, etc.", true),
        param("condition_value", "The value to compare against", true),
        param("condition_background_color", "Background color in hex format, e.g. #FF0000"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        range: "${!this.range}",
        condition_type: "${!this.condition_type}",
        condition_value: "${!this.condition_value}",
        condition_background_color: '${!this.condition_background_color.or("")}',
      },
    ),
    gsTool(
      "gs_copy_range",
      "google_sheets_copy_range",
      "Copy data from one range to another within a Google Sheets spreadsheet, with options for what to paste (values, formatting, etc.).",
      "copy_range",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("source_range", "Source range in A1 notation", true),
        param("destination_range", "Destination range in A1 notation", true),
        param("paste_type", "What to paste: PASTE_NORMAL, PASTE_VALUES, PASTE_FORMAT, PASTE_NO_BORDERS, PASTE_FORMULA"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        source_range: "${!this.source_range}",
        destination_range: "${!this.destination_range}",
        paste_type: '${!this.paste_type.or("PASTE_NORMAL")}',
      },
    ),
    gsTool(
      "gs_copy_worksheet",
      "google_sheets_copy_worksheet",
      "Creates a new worksheet by copying an existing worksheet.",
      "copy_worksheet",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet to copy", true),
        param("destination_spreadsheet_id", "Target spreadsheet ID. Defaults to same spreadsheet if not provided."),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: "${!this.sheet_name}",
        destination_spreadsheet_id: '${!this.destination_spreadsheet_id.or("")}',
      },
    ),
    gsTool(
      "gs_create_worksheet",
      "google_sheets_create_worksheet",
      "Creates a new worksheet in a Google Sheet.",
      "create_worksheet",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("title", "Title for the new worksheet", true),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        title: "${!this.title}",
      },
    ),
    gsTool(
      "gs_clear_rows",
      "google_sheets_clear_rows",
      "Clears the contents of the selected row(s) while keeping the row(s) intact in the spreadsheet.",
      "clear_rows",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("row_number", "Starting row number", true, "number"),
        param("end_row_number", "Ending row number. If not set, only the starting row is cleared.", false, "number"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        row_number: '${!this.row_number}',
        end_row_number: '${!this.end_row_number.or("0")}',
      },
    ),
    gsTool(
      "gs_delete_worksheet",
      "google_sheets_delete_worksheet",
      "Permanently delete a worksheet from a Google Sheets spreadsheet.",
      "delete_worksheet",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet to delete", true),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: "${!this.sheet_name}",
      },
    ),
    gsTool(
      "gs_delete_rows",
      "google_sheets_delete_rows",
      "Deletes the selected row(s) from the spreadsheet. This action removes the row(s) and all associated data.",
      "delete_rows",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("row_number", "Starting row number", true, "number"),
        param("end_row_number", "Ending row number. If not set, only the starting row is deleted.", false, "number"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        row_number: '${!this.row_number}',
        end_row_number: '${!this.end_row_number.or("0")}',
      },
    ),
    gsTool(
      "gs_format_cells",
      "google_sheets_format_cells",
      "Apply date, number, or style formatting (colors, bold, italic, strikethrough) to a range of cells in a Google Sheets spreadsheet.",
      "format_cells",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("range", "A1 notation range to format", true),
        param("bold", "true or false"),
        param("italic", "true or false"),
        param("strikethrough", "true or false"),
        param("background_color", "Hex color, e.g. #FF0000"),
        param("foreground_color", "Hex color, e.g. #000000"),
        param("number_format", "Number format pattern, e.g. #,##0.00"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        range: "${!this.range}",
        bold: '${!this.bold.or("false")}',
        italic: '${!this.italic.or("false")}',
        strikethrough: '${!this.strikethrough.or("false")}',
        background_color: '${!this.background_color.or("")}',
        foreground_color: '${!this.foreground_color.or("")}',
        number_format: '${!this.number_format.or("")}',
      },
    ),
    gsTool(
      "gs_format_row",
      "google_sheets_format_row",
      "Format a row in a specific spreadsheet.",
      "format_row",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("row_number", "Row number to format", true, "number"),
        param("bold", "true or false"),
        param("italic", "true or false"),
        param("strikethrough", "true or false"),
        param("background_color", "Hex color, e.g. #FF0000"),
        param("foreground_color", "Hex color, e.g. #000000"),
        param("number_format", "Number format pattern, e.g. #,##0.00"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        row_number: '${!this.row_number}',
        bold: '${!this.bold.or("false")}',
        italic: '${!this.italic.or("false")}',
        strikethrough: '${!this.strikethrough.or("false")}',
        background_color: '${!this.background_color.or("")}',
        foreground_color: '${!this.foreground_color.or("")}',
        number_format: '${!this.number_format.or("")}',
      },
    ),
    gsTool(
      "gs_rename_worksheet",
      "google_sheets_rename_worksheet",
      "Rename a worksheet in a Google Sheets spreadsheet.",
      "rename_worksheet",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Current name of the worksheet", true),
        param("new_name", "New name for the worksheet", true),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: "${!this.sheet_name}",
        new_name: "${!this.new_name}",
      },
    ),
    gsTool(
      "gs_set_data_validation",
      "google_sheets_set_data_validation",
      "Set data validation rules on a range of cells in Google Sheets to control what data can be entered.",
      "set_data_validation",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("range", "A1 notation range", true),
        param("validation_type", "Type: ONE_OF_LIST, ONE_OF_RANGE, NUMBER_BETWEEN, TEXT_CONTAINS, DATE_IS_VALID, CUSTOM_FORMULA", true),
        param("validation_values", "Comma-separated values for the validation rule", true),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        range: "${!this.range}",
        validation_type: "${!this.validation_type}",
        validation_values: "${!this.validation_values}",
      },
    ),
    gsTool(
      "gs_sort_range",
      "google_sheets_sort_range",
      "Sort data within a specified range in Google Sheets by a chosen column in ascending or descending order.",
      "sort_range",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("range", "A1 notation range to sort", true),
        param("sort_column_index", "0-based column index to sort by", false, "number"),
        param("sort_order", "ASCENDING or DESCENDING"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        range: "${!this.range}",
        sort_column_index: '${!this.sort_column_index.or("0")}',
        sort_order: '${!this.sort_order.or("ASCENDING")}',
      },
    ),
    gsTool(
      "gs_update_row",
      "google_sheets_update_row",
      "Update a row in a specific spreadsheet.",
      "update_row",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("row_number", "Row number to update", true, "number"),
        param("values", "JSON array of new values for the row", true),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        row_number: '${!this.row_number}',
        values: "${!this.values}",
      },
    ),
    gsTool(
      "gs_update_rows",
      "google_sheets_update_rows",
      "Update one or more rows in a specific spreadsheet (with line item support).",
      "update_rows",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("row_number", "Starting row number", true, "number"),
        param("rows", "JSON array of arrays with new values", true),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        row_number: '${!this.row_number}',
        rows: "${!this.rows}",
      },
    ),
    gsTool(
      "gs_lookup_rows",
      "google_sheets_lookup_rows",
      "Find up to 500 rows based on a column and value as line items.",
      "lookup_rows",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("column_name", "Column header to search in", true),
        param("lookup_value", "Value to search for", true),
        param("max_results", "Maximum rows to return, default 500", false, "number"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        column_name: "${!this.column_name}",
        lookup_value: "${!this.lookup_value}",
        max_results: '${!this.max_results.or("500")}',
      },
    ),
    gsTool(
      "gs_find_worksheet",
      "google_sheets_find_worksheet",
      "Finds a worksheet by title.",
      "find_worksheet",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Title of the worksheet to find", true),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: "${!this.sheet_name}",
      },
    ),
    gsTool(
      "gs_get_data_range",
      "google_sheets_get_data_range",
      'Get data from a specific range in a Google Spreadsheet using A1 notation (e.g., "A1:D10", "B2:E5").',
      "get_data_range",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("range", "Range in A1 notation, e.g. A1:D10", true),
        param("include_headers", "true or false, default true"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        range: "${!this.range}",
        include_headers: '${!this.include_headers.or("true")}',
      },
    ),
    gsTool(
      "gs_get_rows",
      "google_sheets_get_rows",
      "Return up to 1,500 rows as a single JSON value or as line items.",
      "get_rows",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("max_results", "Maximum rows to return, default 1500", false, "number"),
        param("include_headers", "true or false"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        max_results: '${!this.max_results.or("1500")}',
        include_headers: '${!this.include_headers.or("true")}',
      },
    ),
    gsTool(
      "gs_get_row",
      "google_sheets_get_row",
      "Get a specific spreadsheet row by its row number (ID). Row 1 is typically the header row.",
      "get_row",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("row_number", "Row number to retrieve (1-based)", true, "number"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        row_number: '${!this.row_number}',
      },
    ),
    gsTool(
      "gs_get_spreadsheet",
      "google_sheets_get_spreadsheet",
      "Get a specific Google Spreadsheet by its ID. Returns the raw spreadsheet data from the Google Sheets API.",
      "get_spreadsheet",
      [
        param("spreadsheet_id", "Spreadsheet ID to retrieve"),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
      },
    ),
    gsTool(
      "gs_lookup_row",
      "google_sheets_lookup_row",
      "Find a specific spreadsheet row based on a column and value. If found, it returns the entire row.",
      "lookup_row",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Name of the worksheet. Defaults to Sheet1."),
        param("column_name", "Column header to search in", true),
        param("lookup_value", "Value to search for", true),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: '${!this.sheet_name.or("Sheet1")}',
        column_name: "${!this.column_name}",
        lookup_value: "${!this.lookup_value}",
      },
    ),
    gsTool(
      "gs_find_or_create_worksheet",
      "google_sheets_find_or_create_worksheet",
      "Finds or creates a specific worksheet.",
      "find_or_create_worksheet",
      [
        param("spreadsheet_id", "Spreadsheet ID. Defaults to the configured spreadsheet if not provided."),
        param("sheet_name", "Title of the worksheet to find or create", true),
      ],
      {
        spreadsheet_id: '${!this.spreadsheet_id.or("")}',
        sheet_name: "${!this.sheet_name}",
      },
    ),
  ],
};
