import { param, type McpToolTemplate, type TemplatePack } from "./types";

function gcTool(
  id: string,
  name: string,
  description: string,
  action: string,
  parameters: ReturnType<typeof param>[],
  configOverrides: Record<string, string | number | boolean> = {},
): McpToolTemplate {
  return {
    id,
    name,
    description,
    parameters,
    processor: {
      component: "google_calendar",
      config: { action, ...configOverrides },
    },
  };
}

export const googleCalendarPack: TemplatePack = {
  id: "google_calendar",
  name: "Google Calendar",
  description: "13 MCP tools for managing Google Calendar events, calendars, and scheduling.",
  sharedConfig: [
    {
      key: "oauth_connection",
      title: "OAuth Connection",
      description: "Google OAuth connection. Set up in Connections page first.",
      type: "dynamic_select",
      required: true,
      dataSource: "connections",
    },
  ],
  templates: [
    gcTool(
      "gc_create_event",
      "google_calendar_create_event",
      "Create a new event on Google Calendar with title, time, location, and attendees.",
      "create_event",
      [
        param("summary", "Event title", true),
        param("start_time", "Start time in RFC3339 format (e.g. 2025-01-15T09:00:00-05:00)", true),
        param("end_time", "End time in RFC3339 format (e.g. 2025-01-15T10:00:00-05:00)", true),
        param("calendar_id", "Calendar ID. Defaults to the configured calendar if not provided."),
        param("description", "Event description text"),
        param("location", "Event location"),
        param("attendees", "Comma-separated attendee email addresses"),
        param("time_zone", "IANA time zone (e.g. America/New_York)"),
        param("visibility", "Event visibility: default, public, private, confidential"),
        param("send_updates", "Notification policy: all, externalOnly, none"),
        param("recurrence", "Comma-separated RRULE recurrence rules"),
      ],
      {
        calendar_id: '${!this.calendar_id.or("")}',
        summary: "${!this.summary}",
        start_time: "${!this.start_time}",
        end_time: "${!this.end_time}",
        description: '${!this.description.or("")}',
        location: '${!this.location.or("")}',
        attendees: '${!this.attendees.or("")}',
        time_zone: '${!this.time_zone.or("")}',
        visibility: '${!this.visibility.or("default")}',
        send_updates: '${!this.send_updates.or("none")}',
        recurrence: '${!this.recurrence.or("")}',
      },
    ),
    gcTool(
      "gc_find_events",
      "google_calendar_find_events",
      "Search for events on Google Calendar by text query or time range.",
      "find_events",
      [
        param("calendar_id", "Calendar ID. Defaults to the configured calendar if not provided."),
        param("query", "Free text search terms to filter events"),
        param("start_time", "Filter events starting after this time (RFC3339)"),
        param("end_time", "Filter events ending before this time (RFC3339)"),
        param("max_results", "Maximum number of events to return", false, "number"),
      ],
      {
        calendar_id: '${!this.calendar_id.or("")}',
        query: '${!this.query.or("")}',
        start_time: '${!this.start_time.or("")}',
        end_time: '${!this.end_time.or("")}',
        max_results: 25,
      },
    ),
    gcTool(
      "gc_get_event",
      "google_calendar_get_event",
      "Get detailed information about a specific Google Calendar event.",
      "get_event",
      [
        param("event_id", "The event identifier", true),
        param("calendar_id", "Calendar ID. Defaults to the configured calendar if not provided."),
      ],
      {
        event_id: "${!this.event_id}",
        calendar_id: '${!this.calendar_id.or("")}',
      },
    ),
    gcTool(
      "gc_update_event",
      "google_calendar_update_event",
      "Update an existing Google Calendar event's details, time, or attendees.",
      "update_event",
      [
        param("event_id", "The event identifier", true),
        param("calendar_id", "Calendar ID. Defaults to the configured calendar if not provided."),
        param("summary", "New event title"),
        param("description", "New event description"),
        param("location", "New event location"),
        param("start_time", "New start time in RFC3339 format"),
        param("end_time", "New end time in RFC3339 format"),
        param("attendees", "Comma-separated attendee email addresses"),
        param("time_zone", "IANA time zone"),
        param("visibility", "Event visibility: default, public, private, confidential"),
        param("send_updates", "Notification policy: all, externalOnly, none"),
        param("recurrence", "Comma-separated RRULE recurrence rules"),
      ],
      {
        event_id: "${!this.event_id}",
        calendar_id: '${!this.calendar_id.or("")}',
        summary: '${!this.summary.or("")}',
        description: '${!this.description.or("")}',
        location: '${!this.location.or("")}',
        start_time: '${!this.start_time.or("")}',
        end_time: '${!this.end_time.or("")}',
        attendees: '${!this.attendees.or("")}',
        time_zone: '${!this.time_zone.or("")}',
        visibility: '${!this.visibility.or("default")}',
        send_updates: '${!this.send_updates.or("none")}',
        recurrence: '${!this.recurrence.or("")}',
      },
    ),
    gcTool(
      "gc_delete_event",
      "google_calendar_delete_event",
      "Delete an event from Google Calendar.",
      "delete_event",
      [
        param("event_id", "The event identifier", true),
        param("calendar_id", "Calendar ID. Defaults to the configured calendar if not provided."),
        param("send_updates", "Notification policy: all, externalOnly, none"),
      ],
      {
        event_id: "${!this.event_id}",
        calendar_id: '${!this.calendar_id.or("")}',
        send_updates: '${!this.send_updates.or("none")}',
      },
    ),
    gcTool(
      "gc_quick_add_event",
      "google_calendar_quick_add_event",
      "Create a Google Calendar event from a natural language description (e.g. 'Meeting with John tomorrow at 3pm').",
      "quick_add_event",
      [
        param("quick_add_text", "Natural language event description that Google will parse", true),
        param("calendar_id", "Calendar ID. Defaults to the configured calendar if not provided."),
      ],
      {
        quick_add_text: "${!this.quick_add_text}",
        calendar_id: '${!this.calendar_id.or("")}',
      },
    ),
    gcTool(
      "gc_find_busy_periods",
      "google_calendar_find_busy_periods",
      "Find busy and free time periods on Google Calendar for scheduling.",
      "find_busy_periods",
      [
        param("start_time", "Start of the time range to check (RFC3339)", true),
        param("end_time", "End of the time range to check (RFC3339)", true),
        param("calendar_id", "Calendar ID. Defaults to the configured calendar if not provided."),
      ],
      {
        start_time: "${!this.start_time}",
        end_time: "${!this.end_time}",
        calendar_id: '${!this.calendar_id.or("")}',
      },
    ),
    gcTool(
      "gc_add_attendees",
      "google_calendar_add_attendees",
      "Add attendees to an existing Google Calendar event.",
      "add_attendees",
      [
        param("event_id", "The event identifier", true),
        param("attendees", "Comma-separated attendee email addresses to add", true),
        param("calendar_id", "Calendar ID. Defaults to the configured calendar if not provided."),
        param("send_updates", "Notification policy: all, externalOnly, none"),
      ],
      {
        event_id: "${!this.event_id}",
        attendees: "${!this.attendees}",
        calendar_id: '${!this.calendar_id.or("")}',
        send_updates: '${!this.send_updates.or("none")}',
      },
    ),
    gcTool(
      "gc_move_event",
      "google_calendar_move_event",
      "Move a Google Calendar event to a different calendar.",
      "move_event",
      [
        param("event_id", "The event identifier", true),
        param("destination_calendar_id", "Target calendar to move the event to", true),
        param("calendar_id", "Source calendar ID. Use 'primary' for the main calendar."),
        param("send_updates", "Notification policy: all, externalOnly, none"),
      ],
      {
        event_id: "${!this.event_id}",
        destination_calendar_id: "${!this.destination_calendar_id}",
        calendar_id: '${!this.calendar_id.or("")}',
        send_updates: '${!this.send_updates.or("none")}',
      },
    ),
    gcTool(
      "gc_find_calendars",
      "google_calendar_find_calendars",
      "List all available Google Calendars for the authenticated user.",
      "find_calendars",
      [
        param("max_results", "Maximum number of calendars to return", false, "number"),
      ],
      {
        max_results: 250,
      },
    ),
    gcTool(
      "gc_get_calendar",
      "google_calendar_get_calendar",
      "Get detailed information about a specific Google Calendar.",
      "get_calendar",
      [
        param("calendar_id", "Calendar ID to retrieve details for", true),
      ],
      {
        calendar_id: "${!this.calendar_id}",
      },
    ),
    gcTool(
      "gc_create_calendar",
      "google_calendar_create_calendar",
      "Create a new Google Calendar.",
      "create_calendar",
      [
        param("calendar_summary", "Name for the new calendar", true),
      ],
      {
        calendar_summary: "${!this.calendar_summary}",
      },
    ),
    gcTool(
      "gc_find_or_create_event",
      "google_calendar_find_or_create_event",
      "Find an existing Google Calendar event matching the criteria, or create a new one if not found.",
      "find_or_create_event",
      [
        param("summary", "Event title to search for or create with", true),
        param("start_time", "Start time in RFC3339 format", true),
        param("end_time", "End time in RFC3339 format", true),
        param("calendar_id", "Calendar ID. Defaults to the configured calendar if not provided."),
        param("description", "Event description text"),
        param("location", "Event location"),
        param("attendees", "Comma-separated attendee email addresses"),
        param("query", "Additional search terms to help find existing event"),
        param("time_zone", "IANA time zone"),
        param("visibility", "Event visibility: default, public, private, confidential"),
        param("send_updates", "Notification policy: all, externalOnly, none"),
        param("recurrence", "Comma-separated RRULE recurrence rules"),
      ],
      {
        calendar_id: '${!this.calendar_id.or("")}',
        summary: "${!this.summary}",
        start_time: "${!this.start_time}",
        end_time: "${!this.end_time}",
        description: '${!this.description.or("")}',
        location: '${!this.location.or("")}',
        attendees: '${!this.attendees.or("")}',
        query: '${!this.query.or("")}',
        time_zone: '${!this.time_zone.or("")}',
        visibility: '${!this.visibility.or("default")}',
        send_updates: '${!this.send_updates.or("none")}',
        recurrence: '${!this.recurrence.or("")}',
      },
    ),
  ],
};
