#!/usr/bin/env bash
#
# Installs Qaynaq the quick way.
#
# Requires curl, grep, cut, tar, uname, chmod, mv, rm.

[[ $- = *i* ]] && echo "Don't source this script!" && return 10

header() {
	cat 1>&2 <<EOF
Qaynaq Installer

Website: https://qaynaq.io
Repo:    https://github.com/qaynaq/qaynaq

EOF
}

check_cmd() {
	command -v "$1" > /dev/null 2>&1
}

check_tools() {
	Tools=("curl" "grep" "cut" "tar" "uname" "chmod" "mv" "rm")

	for tool in ${Tools[*]}; do
		if ! check_cmd $tool; then
			echo "Aborted, missing $tool, sorry!"
			exit 6
		fi
	done
}

install_qaynaq()
{
	trap 'echo -e "Aborted, error $? in command: $BASH_COMMAND"; trap ERR; exit 1' ERR

	if [[ "$#" -eq 2 ]]; then
		qaynaq_tag="v$1"
		qaynaq_version="$1"
		qaynaq_install_path="$2"
	elif [[ "$#" -eq 1 ]]; then
		qaynaq_tag="v$1"
		qaynaq_version=$1
		qaynaq_install_path="/usr/local/bin"
	elif [[ "$#" -eq 0 ]]; then
		qaynaq_tag=$(curl -s https://api.github.com/repos/qaynaq/qaynaq/releases/latest | grep 'tag_name' | cut -d\" -f4)
		qaynaq_version=$(echo ${qaynaq_tag} | cut -c2-)
		qaynaq_install_path="/usr/local/bin"
	else
		echo "Too many arguments."
		exit 1
	fi

	qaynaq_os="unsupported"
	qaynaq_arch="unknown"
	qaynaq_arm=""

	header
	check_tools

	if [[ -n "$PREFIX" ]]; then
		qaynaq_install_path="$PREFIX/bin"
	fi

	if [[ ! -d $qaynaq_install_path ]]; then
		qaynaq_install_path="/usr/bin"
	fi

	((EUID)) && sudo_cmd="sudo"

	#########################
	# Which OS and version? #
	#########################

	qaynaq_bin="qaynaq"
	qaynaq_dl_ext=".tar.gz"

	unamem="$(uname -m)"
	if [[ $unamem == *aarch64* ]]; then
		qaynaq_arch="arm64"
	elif [[ $unamem == *arm64* ]]; then
		qaynaq_arch="arm64"
	elif [[ $unamem == *64* ]]; then
		qaynaq_arch="amd64"
	elif [[ $unamem == *armv7l* ]]; then
		qaynaq_arch="armv7"
	else
		echo "Aborted, unsupported or unknown architecture: $unamem"
		return 2
	fi

	unameu="$(tr '[:lower:]' '[:upper:]' <<<$(uname))"
	if [[ $unameu == *DARWIN* ]]; then
		qaynaq_os="darwin"
	elif [[ $unameu == *LINUX* ]]; then
		qaynaq_os="linux"
	elif [[ $unameu == *WIN* || $unameu == MSYS* ]]; then
		sudo_cmd=""
		qaynaq_os="windows"
		qaynaq_bin=$qaynaq_bin.exe
		qaynaq_dl_ext=".zip"
	else
		echo "Aborted, unsupported or unknown os: $unameu"
		return 6
	fi

	########################
	# Download and extract #
	########################

	echo "Downloading Qaynaq for ${qaynaq_os}/${qaynaq_arch}${qaynaq_arm}..."

	qaynaq_file="qaynaq_${qaynaq_os}_${qaynaq_arch}${qaynaq_arm}${qaynaq_dl_ext}"
	qaynaq_url="https://github.com/qaynaq/qaynaq/releases/download/${qaynaq_tag}/qaynaq_${qaynaq_version}_${qaynaq_os}_${qaynaq_arch}${qaynaq_arm}.tar.gz"

	dl="/tmp/$qaynaq_file"
	rm -rf -- "$dl"

	curl -fsSL "$qaynaq_url" -o "$dl"

	echo "Extracting..."
	case "$qaynaq_file" in
		*.tar.gz) tar -xzf "$dl" -C "$PREFIX/tmp/" "$qaynaq_bin" ;;
	esac
	chmod +x "$PREFIX/tmp/$qaynaq_bin"

	echo "Putting qaynaq in $qaynaq_install_path (may require password)"
	if [ -n "$sudo_cmd" ] && [ -n "$(find "$qaynaq_install_path" -prune -user "$(id -u)")" ]; then
		sudo_cmd=""
	fi
	$sudo_cmd mv "$PREFIX/tmp/$qaynaq_bin" "$qaynaq_install_path/$qaynaq_bin"
	$sudo_cmd rm -- "$dl"

	$qaynaq_install_path/$qaynaq_bin --version
	if ! check_cmd qaynaq; then
		echo "Do not forget to add $qaynaq_install_path to your PATH!"
	fi

	echo "Successfully installed"
	trap ERR
	return 0
}

install_qaynaq $@
