/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/quickstart",
        "getting-started/installation",
        "getting-started/configuration",
        "getting-started/authentication",
      ],
    },
    {
      type: "category",
      label: "Concepts",
      items: [
        "concepts/architecture",
        "concepts/flows",
        "concepts/components",
        "concepts/files",
        "concepts/validation",
        "concepts/testing-flows",
      ],
    },
    {
      type: "category",
      label: "Components",
      items: [
        {
          type: "category",
          label: "Inputs",
          link: { type: "doc", id: "components/inputs/index" },
          items: [
            "components/inputs/generate",
            "components/inputs/http-client",
            "components/inputs/http-server",
            "components/inputs/kafka",
            "components/inputs/amqp-0-9",
            "components/inputs/broker",
            "components/inputs/cdc-mysql",
            "components/inputs/mcp-tool",
            "components/inputs/shopify",
            "components/inputs/file",
          ],
        },
        {
          type: "category",
          label: "Processors",
          link: { type: "doc", id: "components/processors/index" },
          items: [
            "components/processors/ai-gateway",
            "components/processors/nlp-extract-features",
            "components/processors/nlp-classify-text",
            "components/processors/nlp-classify-tokens",
            "components/processors/nlp-zero-shot-classify",
            "components/processors/google-calendar",
            "components/processors/google-drive",
            "components/processors/google-sheets",
            "components/processors/shopify",
            "components/processors/mapping",
            "components/processors/command",
            "components/processors/python",
            "components/processors/json-schema",
            "components/processors/catch",
            "components/processors/switch",
            "components/processors/schema-registry-decode",
            "components/processors/http-client",
            "components/processors/sql-raw",
            "components/processors/sql-select",
            "components/processors/sql-insert",
          ],
        },
        {
          type: "category",
          label: "Outputs",
          link: { type: "doc", id: "components/outputs/index" },
          items: [
            "components/outputs/http-client",
            "components/outputs/kafka",
            "components/outputs/amqp-0-9",
            "components/outputs/sql-insert",
            "components/outputs/sync-response",
            "components/outputs/switch",
            "components/outputs/broker",
          ],
        },
        {
          type: "category",
          label: "Scanners",
          link: { type: "doc", id: "components/scanners/index" },
          items: [
            "components/scanners/rag-chunker",
            "components/scanners/lines",
            "components/scanners/csv",
            "components/scanners/re-match",
            "components/scanners/json-documents",
            "components/scanners/xml-documents",
            "components/scanners/avro",
            "components/scanners/chunker",
            "components/scanners/tar",
            "components/scanners/to-the-end",
            "components/scanners/skip-bom",
            "components/scanners/decompress",
          ],
        },
        "components/caches",
      ],
    },
    {
      type: "category",
      label: "Guides",
      items: [
        "guides/connections",
        "guides/google-oauth-setup",
        "guides/mcp-server",
        "guides/mcp-remote-servers",
        "guides/mcp-local-servers",
        "guides/mcp-oauth",
        {
          type: "category",
          label: "Templates",
          link: { type: "doc", id: "guides/templates/index" },
          items: [
            "guides/templates/google-calendar",
            "guides/templates/google-drive",
            "guides/templates/google-sheets",
            "guides/templates/shopify",
          ],
        },
        "guides/scaling-workers",
        "guides/keycloak-authentication",
        "guides/access-control",
      ],
    },
    {
      type: "category",
      label: "Reference",
      items: [
        "reference/cli",
        "reference/environment-variables",
      ],
    },
  ],
};

module.exports = sidebars;
